<?php

namespace App\Services;

use App\Models\NotificationDelivery;
use App\Models\User;
use App\Notifications\SystemMessageNotification;
use Illuminate\Http\Request;
use Throwable;

/**
 * Notification dispatch primitive for phase-one implementation.
 *
 * Responsibilities:
 *  1) Send database notifications to a user.
 *  2) Track delivery status in notification_deliveries table.
 *  3) Emit audit entries for sent/failed attempts.
 */
class NotificationDispatcher
{
    public function __construct(
        private readonly Request $request,
        private readonly AuditLogger $auditLogger,
    ) {}

    /**
     * Send a database notification and write a delivery tracking row.
     *
     * Example input:
     *   sendDatabase(
     *     recipient: $user,
     *     type: 'approval.pending',
     *     title: 'Approval Needed',
     *     message: 'Payout #901 needs review',
     *     payload: ['entity_type' => 'payout_request', 'entity_id' => 901],
     *   )
     *
     * Example result:
     *   NotificationDelivery { status: 'sent', channel: 'database', delivered_at: now() }
     *
     * @param  array<string, mixed>  $payload
     */
    public function sendDatabase(
        User $recipient,
        string $type,
        string $title,
        string $message,
        array $payload = [],
        ?User $actor = null,
    ): NotificationDelivery {
        // Create a pending ledger row first so failed attempts are still traceable.
        $delivery = NotificationDelivery::query()->create([
            'recipient_user_id' => $recipient->id,
            'notification_type' => $type,
            'channel' => 'database',
            'status' => 'pending',
            'title' => $title,
            'message' => $message,
            'payload' => $payload !== [] ? $payload : null,
            'correlation_id' => $this->request->attributes->get('correlation_id'),
        ]);

        try {
            $recipient->notify(new SystemMessageNotification(
                type: $type,
                title: $title,
                message: $message,
                payload: $payload,
            ));

            // Grab the latest database notification generated by the call above.
            $latestNotification = $recipient->notifications()->latest('created_at')->first();

            $delivery->update([
                'notification_id' => $latestNotification?->id,
                'status' => 'sent',
                'delivered_at' => now(),
                'failure_reason' => null,
            ]);

            $this->auditLogger->record(
                action: 'notification.sent',
                subject: $delivery,
                actor: $actor,
                context: [
                    'recipient_user_id' => $recipient->id,
                    'notification_type' => $type,
                    'channel' => 'database',
                ],
            );

            return $delivery->refresh();
        } catch (Throwable $exception) {
            $delivery->update([
                'status' => 'failed',
                'failure_reason' => $exception->getMessage(),
            ]);

            $this->auditLogger->record(
                action: 'notification.failed',
                subject: $delivery,
                actor: $actor,
                context: [
                    'recipient_user_id' => $recipient->id,
                    'notification_type' => $type,
                    'channel' => 'database',
                    'error' => $exception->getMessage(),
                ],
            );

            return $delivery->refresh();
        }
    }
}
